import { useState, useRef, useEffect } from 'react';

interface Message {
  id: string;
    role: 'user' | 'assistant';
      content: string;
        sources?: number;
          timestamp: Date;
          }

          const SUGGESTED_QUESTIONS = [
            'What did the team ship this sprint?',
              'Which PRs were merged this week?',
                'Who opened the most issues recently?',
                  'Summarize recent activity in the main repo',
                  ];

                  export default function AskAI() {
                    const [messages, setMessages] = useState<Message[]>([]);
                      const [input, setInput] = useState('');
                        const [loading, setLoading] = useState(false);
                          const bottomRef = useRef<HTMLDivElement>(null);

                            useEffect(() => {
                                bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
                                  }, [messages]);

                                    const sendMessage = async (question: string) => {
                                        if (!question.trim() || loading) return;

                                            const userMsg: Message = {
                                                  id: crypto.randomUUID(),
                                                        role: 'user',
                                                              content: question,
                                                                    timestamp: new Date(),
                                                                        };

                                                                            setMessages((prev) => [...prev, userMsg]);
                                                                                setInput('');
                                                                                    setLoading(true);

                                                                                        try {
                                                                                              const res = await fetch(`${import.meta.env.VITE_API_URL}/rag-query`, {
                                                                                                      method: 'POST',
                                                                                                              headers: {
                                                                                                                        'Content-Type': 'application/json',
                                                                                                                                  Authorization: `Bearer ${localStorage.getItem('access_token')}`,
                                                                                                                                          },
                                                                                                                                                  body: JSON.stringify({
                                                                                                                                                            question,
                                                                                                                                                                      teamId: localStorage.getItem('team_id') || 'default',
                                                                                                                                                                                userId: localStorage.getItem('user_id'),
                                                                                                                                                                                        }),
                                                                                                                                                                                              });
                                                                                                                                                                                              
                                                                                                                                                                                                    const data = await res.json();
                                                                                                                                                                                                    
                                                                                                                                                                                                          const aiMsg: Message = {
                                                                                                                                                                                                                  id: crypto.randomUUID(),
                                                                                                                                                                                                                          role: 'assistant',
                                                                                                                                                                                                                                  content: data.answer || 'Sorry, I could not find an answer.',
                                                                                                                                                                                                                                          sources: data.sources,
                                                                                                                                                                                                                                                  timestamp: new Date(),
                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                              setMessages((prev) => [...prev, aiMsg]);
                                                                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                                                                        setMessages((prev) => [
                                                                                                                                                                                                                                                                                ...prev,
                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                  id: crypto.randomUUID(),
                                                                                                                                                                                                                                                                                                            role: 'assistant',
                                                                                                                                                                                                                                                                                                                      content: 'Something went wrong. Please try again.',
                                                                                                                                                                                                                                                                                                                                timestamp: new Date(),
                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                              ]);
                                                                                                                                                                                                                                                                                                                                                  } finally {
                                                                                                                                                                                                                                                                                                                                                        setLoading(false);
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                    <div className="flex flex-col h-screen bg-gray-950 text-gray-100">
                                                                                                                                                                                                                                                                                                                                                                          {/* Header */}
                                                                                                                                                                                                                                                                                                                                                                                <div className="border-b border-gray-800 px-6 py-4">
                                                                                                                                                                                                                                                                                                                                                                                        <h1 className="text-xl font-semibold text-white">Ask AI</h1>
                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sm text-gray-400">Powered by AWS Bedrock Claude 3 + Pinecone RAG</p>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                            {/* Messages */}
                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex-1 overflow-y-auto px-6 py-4 space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                          {messages.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-12 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-400 mb-6 text-lg">What would you like to know about your team?</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-w-2xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {SUGGESTED_QUESTIONS.map((q) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={q}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => sendMessage(q)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="text-left px-4 py-3 rounded-xl border border-gray-700 bg-gray-900 hover:bg-gray-800 hover:border-indigo-500 text-sm text-gray-300 transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {q}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {messages.map((msg) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`max-w-2xl rounded-2xl px-4 py-3 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          msg.role === 'user'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? 'bg-indigo-600 text-white ml-12'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : 'bg-gray-800 text-gray-100 mr-12'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm leading-relaxed whitespace-pre-wrap">{msg.content}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {msg.sources !== undefined && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs text-gray-400 mt-2">{msg.sources} source{msg.sources !== 1 ? 's' : ''} retrieved</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex justify-start">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-gray-800 rounded-2xl px-4 py-3 mr-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex gap-1.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div ref={bottomRef} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Input */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="border-t border-gray-800 px-6 py-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex gap-3 max-w-3xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setInput(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onKeyDown={(e) => e.key === 'Enter' && sendMessage(input)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Ask anything about your team's activity..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="flex-1 bg-gray-800 border border-gray-700 rounded-xl px-4 py-3 text-sm text-gray-100 placeholder-gray-500 focus:outline-none focus:border-indigo-500 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => sendMessage(input)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    disabled={loading || !input.trim()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="px-5 py-3 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-40 disabled:cursor-not-allowed rounded-xl text-sm font-medium text-white transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Send
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
